module.exports = {
  LOGIN: {
    SET_SESSION_ID: "LOGIN.SET_SESSION_ID",
    SET_WX_AUTH_ID  : 'LOGIN.SET_WX_AUTH_ID',
  },
  USER: {
    SET_USER_INFO: "USER.SET_USER_INFO",
    SET_WX_USER_INFO: "USER.SET_WX_USER_INFO",
  },
  CHECKOUT: {
    SET_SETTLEMENT: "CHECKOUT.SET_SETTLEMENT",
    SET_ADDRESS: "CHECKOUT.SET_ADDRESS",
    SET_TYPE: "CHECKOUT.SET_TYPE",
    SET_INVOICE: "CHECKOUT.SET_INVOICE",
    SET_COUPON: "CHECKOUT.SET_COUPON",
    SET_COUPON_DATA: "CHECKOUT.SET_COUPON_DATA",
    SET_REMARK: "CHECKOUT.SET_REMARK",
    CHANGE_REMARK: "CHECKOUT.CHANGE_REMARK",
    RESET_STATE: "CHECKOUT.RESET_STATE",
    SET_DIRECT_DATA: "CHECKOUT.SET_DIRECT_DATA",
    SET_BALANCE:'CHECKOUT.SET_BALANCE',
    SET_BALANCE_STATE:'CHECKOUT.SET_BALANCE_STATE',
  }
};
